# Generated by Django 5.1.6 on 2025-05-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_author_full_name'),
        ),
    ]
