# Generated by Django 5.1.6 on 2025-05-07 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_author_unique_author_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to='books.book')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ISBN')),
                ('number_of_pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Liczba stron')),
                ('language', models.CharField(blank=True, max_length=50, verbose_name='Język')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='Wydawca')),
            ],
            options={
                'verbose_name_plural': 'Szczegóły książek',
            },
        ),
    ]
